### ISSUE TITLE
install.directory vs. wlp.install.dir, etc.

### ISSUE THREAD

**Issue by scottkurz** [WASdev/tool.artisan.core#1]
Just wondering if we'd considered using the server-side properties as the Maven properties instead of inventing new Maven property names for this, wlp.user.dir, server.config.dir, etc.    Perhaps some of the same questions could be asked of the Liberty maven plugin itself.     The more layers that are built around the core Maven the nicer it would seem to be to settle on a given name.

**Comment by katheris** [comment]
Hi, I generally followed along with what the Liberty maven plugin was doing. Would definitely be worth having a discussion with jgawor about it, as he handles a lot of the plugin stuff. We should try to get to a consistent naming system.

**Comment by scottkurz** [comment]
Took a closer look at the Liberty maven plugin and it does seem to start us off fine here.  So maybe this is already covered.   (I think I got confused by the -DwlpInstallDir in the doc but that's just building the plugin).  Thanks.
